server:
  servlet:
    context-path: /produdoro/api

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://mosesgdo:xOU7GNZTkFLjCCbF@cluster0.x4gnvs1.mongodb.net/Cluster0?retryWrites=true&w=majority}
      auto-index-creation: true






